//
// Created by Connor Baker on 2019-04-17.
//

#ifndef VEC_C_PROJ_DEFS_H
#define VEC_C_PROJ_DEFS_H

#include "vec.h"

DEFINE_VEC(int)

DEFINE_PROTO_NEW_VEC(int)
DEFINE_PROTO_DEL_VEC(int)
DEFINE_PROTO_REPEAT(int)
DEFINE_PROTO_FOLDL(int)
DEFINE_PROTO_FOLDR(int)
DEFINE_PROTO_ITERATE(int)
DEFINE_PROTO_CONCAT(int)
DEFINE_PROTO_PRINT(int)

DEFINE_NEW_VEC(int)
DEFINE_DEL_VEC(int)
DEFINE_REPEAT(int)
DEFINE_FOLDL(int)
DEFINE_FOLDR(int)
DEFINE_ITERATE(int)
DEFINE_CONCAT(int)
DEFINE_PRINT(int)

#endif //VEC_C_PROJ_DEFS_H
