//
// Created by Connor Baker on 2019-04-17.
//

#ifndef VEC_C_PROJ_DEFS_H
#define VEC_C_PROJ_DEFS_H

// Change this to desired type
#define TYPE int

#include "vec.h"

DEFINE_VEC(TYPE)

DEFINE_PROTO_NEW_VEC(TYPE)
DEFINE_PROTO_DEL_VEC(TYPE)
DEFINE_PROTO_REPEAT(TYPE)
DEFINE_PROTO_FOLDL(TYPE)
DEFINE_PROTO_FOLDR(TYPE)
DEFINE_PROTO_ITERATE(TYPE)
DEFINE_PROTO_CONCAT(TYPE)
DEFINE_PROTO_PRINT(TYPE)
DEFINE_PROTO_HEAD(TYPE)

DEFINE_NEW_VEC(TYPE)
DEFINE_DEL_VEC(TYPE)
DEFINE_REPEAT(TYPE)
DEFINE_FOLDL(TYPE)
DEFINE_FOLDR(TYPE)
DEFINE_ITERATE(TYPE)
DEFINE_CONCAT(TYPE)
DEFINE_PRINT(TYPE)
DEFINE_HEAD(TYPE)

#endif //VEC_C_PROJ_DEFS_H
